name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - id: token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.FRECKLE_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.FRECKLE_AUTOMATION_PRIVATE_KEY }}
          repositories: megarepo

      # Run once with settings that are sure to find nothing (this repository
      # has nothing being kept up to date).
      - uses: ./
        with:
          dry-run: 1

      # Run again with settings that are sure to find something (this repository
      # is really active and should always have open dependabot PRs).
      - uses: ./
        with:
          quarantine-days: -1
          github-token: ${{ steps.token.outputs.token }}
          github-repository: freckle/megarepo
          dry-run: 1

      # Run again exercising exclude-title-regex
      - uses: ./
        with:
          exclude-title-regex: 'in /qa$'
          quarantine-days: -1
          github-token: ${{ steps.token.outputs.token }}
          github-repository: freckle/megarepo
          dry-run: 1

      # Run as if we were a Dependabot-PR, so we can see the comment
      - uses: ./
        with:
          remove-reviewers: false
          github-actor: 'dependabot[bot]'

      # And test the when-message conditional
      - uses: ./
        with:
          quarantine-days: -1
          remove-reviewers: false
          github-actor: 'dependabot[bot]'
